//! Static file serving module
//!
//! This module provides functionality for serving static files,
//! such as `LastFM` fetcher output.

use tower_http::services::ServeDir;

/// Creates a `ServeDir` service for serving static files from the `/static` directory.
///
/// # Returns
/// * `ServeDir` - A service configured to serve files from the `static` directory.
///
/// # Notes
/// Currently serves files generated by the `LastFM` Fetcher.
#[must_use]
pub fn static_files_service() -> ServeDir {
    ServeDir::new("static")
}
